[build]
      publish = "."
    
    [[redirects]]
      from = "/scraper"
      to = "/scraper.html"
      status = 301
    
    [[redirects]]
      from = "/dashboard"
      to = "/index.html"
      status = 301
    
    [[redirects]]
      from = "/api/*"
      to = "/404.html"
      status = 404
    
    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200
    