[build]
  publish = "."

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
