[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[[redirects]]
  from = "/scraper"
  to = "/scraper.html"
  status = 301

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 301